web:
 image: nginx:latest
 ports:
 - "80:80"
 expose:
 - "80"
 volumes:
 - ./moodleroot:/var/www/html:rw
 - ./moodledata:/var/www/moodledata:rw
 - ./config/default:/etc/nginx/sites-enabled/default
 - ./config/nginx.conf:/etc/nginx/nginx.conf
 - ./config/fastcgi_params:/etc/nginx/fastcgi_params
 links:
 - php
php:
 #image: php:7.2-fpm
 build: './docker/php'
 #command: apt-get install php-xmlrpc
 user: "1000:1000"
 volumes:
 - ./config/www.conf:/usr/local/etc/php-fpm.d/www.conf
 - ./config/php.ini:/usr/local/etc/php/php.ini-production
 - ./moodleroot:/var/www/html:rw 
 - ./moodledata:/var/www/moodledata:rw
